services:
  jupyter:
    build: .
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/workspace/notebooks
      - ./src:/workspace/src
      - ./data:/workspace/data
      - ./scripts:/workspace/scripts
      - ./assets:/workspace/assets
    environment:
      - PYTHONPATH=/workspace:/workspace/src
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
    command: >
      jupyter lab --ip=0.0.0.0 --port=8888 --no-browser --allow-root --NotebookApp.token='pde2026'

  spark-master:
    build: .
    ports:
      - "8080:8080"
      - "7077:7077"
    volumes:
      - ./data:/workspace/data
      - ./src:/workspace/src
    command: >
      bash -c "start-master.sh && tail -f /dev/null"

  spark-worker-1:
    build: .
    depends_on: [ spark-master ]
    environment:
      - SPARK_WORKER_CORES=8
      - SPARK_WORKER_MEMORY=28g
      - CUDA_VISIBLE_DEVICES=0
      - PYTHONPATH=/workspace:/workspace/src
    volumes:
      - ./data:/workspace/data
      - ./src:/workspace/src
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ '0' ]
              capabilities: [ gpu ]
    command: >
      bash -c "start-worker.sh spark://spark-master:7077 && tail -f /dev/null"

  spark-worker-2:
    build: .
    depends_on: [ spark-master ]
    environment:
      - SPARK_WORKER_CORES=8
      - SPARK_WORKER_MEMORY=28g
      - CUDA_VISIBLE_DEVICES=0
      - PYTHONPATH=/workspace:/workspace/src
    volumes:
      - ./data:/workspace/data
      - ./src:/workspace/src
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ '1' ]
              capabilities: [ gpu ]
    command: >
      bash -c "start-worker.sh spark://spark-master:7077 && tail -f /dev/null"

  spark-worker-3:
    build: .
    depends_on: [ spark-master ]
    environment:
      - SPARK_WORKER_CORES=8
      - SPARK_WORKER_MEMORY=28g
      - CUDA_VISIBLE_DEVICES=0
      - PYTHONPATH=/workspace:/workspace/src
    volumes:
      - ./data:/workspace/data
      - ./src:/workspace/src
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ '2' ]
              capabilities: [ gpu ]
    command: >
      bash -c "start-worker.sh spark://spark-master:7077 && tail -f /dev/null"

  spark-worker-4:
    build: .
    depends_on: [ spark-master ]
    environment:
      - SPARK_WORKER_CORES=8
      - SPARK_WORKER_MEMORY=28g
      - CUDA_VISIBLE_DEVICES=0
      - PYTHONPATH=/workspace:/workspace/src
    volumes:
      - ./data:/workspace/data
      - ./src:/workspace/src
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              device_ids: [ '3' ]
              capabilities: [ gpu ]
    command: >
      bash -c "start-worker.sh spark://spark-master:7077 && tail -f /dev/null"
