# conf/spark-defaults.conf
# Applied to all Spark sessions in this cluster.

spark.serializer                org.apache.spark.serializer.KryoSerializer
spark.sql.shuffle.partitions    32
spark.ui.showConsoleProgress    true
spark.eventLog.enabled          false
